@MinimalApiWithDapper.Web_HostAddress = https://localhost:7247

GET {{MinimalApiWithDapper.Web_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MinimalApiWithDapper.Web_HostAddress}}/employee

###
